format:
  html:
    toc: true  # Enables the table of contents
    theme:
      light: [cosmo, theme.scss]  # Light theme customization
      dark: [cosmo, theme-dark.scss]  # Dark theme customization
    code-copy: true  # Enables copy button for code blocks
    code-overflow: wrap  # Wraps long code lines
    css: styles.css  # Custom CSS file
    include-after-body: js.html  # Custom JS to include after body
    grid:
      sidebar-width: 250px  # Width of the sidebar
      body-width: 900px  # Width of the main body content
      margin-width: 300px  # Width of the page margins
    search: false  # Disables the search button
