project:
  type: website

website:
  title: "Taif Children's Hospital"
  image: "quarto-dark-bg.jpeg"
  favicon: "favicon.png"
  site-url: https://quarto.org
  
  navbar:
    background: light
    logo: quarto.png
    logo-alt: "Quarto logo."
    title: false
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Gallery"
        href: docs/gallery/index.qmd
     
      

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px



